name: prodigy_fwd_04_realtime_chat_application
description: A real-time chat application using Flutter and Firebase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.27.0

  # Firebase Authentication
  firebase_auth: ^4.17.0

  # Cloud Firestore (Real-time messaging)
  cloud_firestore: ^4.15.0

  # Date formatting
  intl: ^0.19.0

  # UI icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
